### ISSUE TITLE
what happened to Gaphinsight.com?

### ISSUE THREAD

**Issue by ghost** [CarloNicolini/GraphInsight#1]
@CarloNicolini Hi there, I am curious to what happened to your main company, and website gaphinsight.com? and why are your graphinsight pro versions released here?

**Comment by CarloNicolini** [comment]
what happens to 99% of the start-ups. the project died. It was more a proof
of concept at the time than a true commercial product and we were students
with too little support.
Sad...eventually we decided to host it on github to save hosting costs of
the domain.

It is open for everyone who want to improve it and update it.
Qt5 support without all the hassles of outdated glu libs and immediate
rendering mode would be great.

Il Gio 3 Mag 2018 23:03 christophered <notifications@github.com> ha scritto:
